### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку Test01. Virt Mem Max Жаворонков Эдгар

### ISSUE THREAD

**Issue by edgarzhavoronkov** [edgarzhavoronkov/au-linux-kernel-spring-2016#3]
https://github.com/edgarzhavoronkov/au-linux-kernel-spring-2016/commit/3ad6d27c3a434a9db47d4124bf1413202ae06d8e
https://github.com/edgarzhavoronkov/au-linux-kernel-spring-2016/commit/0611d9f65e606a361936fac1e725c51f04bf8040

**Comment by eabatalov** [comment]
Your implementation doesn't allocate the maximal amount of memory because you allocate each available size only twice. Suppose we have 10 non-continuous pages available in address space. You'll allocate only 2.

50 points out of 100 for the task.

**Comment by edgarzhavoronkov** [comment]
@eabatalov кажется, в табличке оценки нет =(

**Comment by eabatalov** [comment]
Да, извините. Поправил :)
